# Generated by Django 3.1.7 on 2021-03-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StuffTracker', '0002_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StuffTracker.myuser'),
        ),
    ]
