# Generated by Django 4.0.3 on 2022-04-25 13:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionassignment',
            name='permissionAPIName',
        ),
        migrations.RemoveField(
            model_name='permissionassignment',
            name='userID',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Teaching Assistant', 'TEACHING_ASSISTANT'), ('Instructor', 'INSTRUCTOR'), ('Admin', 'ADMIN')], default='Teaching Assistant', max_length=30),
        ),
        migrations.AddField(
            model_name='section',
            name='sectionType',
            field=models.CharField(choices=[('Discussion', 'DISCUSSION'), ('Lab', 'LAB')], default='Discussion', max_length=30),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackendWork.myuser'),
        ),
        migrations.AlterField(
            model_name='section',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendWork.classlist'),
        ),
        migrations.AlterField(
            model_name='section',
            name='TA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendWork.myuser'),
        ),
        migrations.AlterField(
            model_name='section',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'SUNDAY'), ('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionAssignment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
