# Generated by Django 4.0.3 on 2022-04-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0002_remove_permissionassignment_permissionapiname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='endTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
