# Generated by Django 4.0.3 on 2022-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0004_rename_ta_section_assigneduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='assignedClass',
        ),
        migrations.AddField(
            model_name='myuser',
            name='assignedClasses',
            field=models.ManyToManyField(null=True, to='BackendWork.classlist'),
        ),
    ]
