# Generated by Django 4.0.3 on 2022-05-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0005_remove_myuser_assignedclass_myuser_assignedclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
