# Generated by Django 4.0.3 on 2022-05-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0006_alter_classlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='schedule',
        ),
        migrations.AddField(
            model_name='section',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
