# Generated by Django 4.0.3 on 2022-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0007_remove_section_schedule_section_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
