# Generated by Django 4.0.3 on 2022-05-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0009_alter_section_sectionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='assignedClasses',
            field=models.ManyToManyField(blank=True, null=True, to='BackendWork.classlist'),
        ),
        migrations.AlterField(
            model_name='section',
            name='assignedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendWork.myuser'),
        ),
    ]
