# Generated by Django 4.0.3 on 2022-05-10 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0010_alter_myuser_assignedclasses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='endTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='section',
            name='startTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
